/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kangagui;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Droti
 */
public class KangaFoablak extends javax.swing.JFrame {

    public KangaFoablak() {
        initComponents();
        setTitle("Kanga Babahordozó Klub kölcsönzési rendszer");
        setLocationRelativeTo(null);

        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                dispose();
                System.exit(0);
            }

        });

        dEmailBelepes.setTitle("E-mail cím megadása");
        dEmailBelepes.setLocationRelativeTo(this);

        UIManager.put("OptionPane.cancelButtonText", "Mégsem");
        UIManager.put("OptionPane.noButtonText", "Nem");
        UIManager.put("OptionPane.okButtonText", "OK");
        UIManager.put("OptionPane.yesButtonText", "Igen");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dEmailBelepes = new javax.swing.JDialog();
        btOk = new javax.swing.JButton();
        btMegsem = new javax.swing.JButton();
        tfJelszo = new javax.swing.JPasswordField();
        tfEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        KangaMenu = new javax.swing.JMenuBar();
        menuKilepes = new javax.swing.JMenu();
        jmKilepes = new javax.swing.JMenuItem();
        menuKolcsonzes = new javax.swing.JMenu();
        mKolcsonzes = new javax.swing.JMenuItem();
        mVisszavetel = new javax.swing.JMenuItem();
        menuEmlekezteto = new javax.swing.JMenuItem();
        menuElemek = new javax.swing.JMenu();
        mTagokKezezelese = new javax.swing.JMenuItem();
        mHordozokKezelese = new javax.swing.JMenuItem();
        menuLekerdezes = new javax.swing.JMenu();
        mLekerdez = new javax.swing.JMenuItem();

        dEmailBelepes.setMinimumSize(new java.awt.Dimension(400, 237));

        btOk.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });

        btMegsem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btMegsem.setText("Mégsem");
        btMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMegsemActionPerformed(evt);
            }
        });

        tfJelszo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("E-mail cím");
        jLabel2.setToolTipText("\"Azt az e-mail címet adja meg, amelyről az emlékeztetőt küldeni szeretné.\"");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Jelszó");
        jLabel3.setToolTipText("\"Az e-mail címhez tartozó jelszó\"");

        javax.swing.GroupLayout dEmailBelepesLayout = new javax.swing.GroupLayout(dEmailBelepes.getContentPane());
        dEmailBelepes.getContentPane().setLayout(dEmailBelepesLayout);
        dEmailBelepesLayout.setHorizontalGroup(
            dEmailBelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dEmailBelepesLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(dEmailBelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(77, 77, 77)
                .addGroup(dEmailBelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dEmailBelepesLayout.createSequentialGroup()
                        .addGroup(dEmailBelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfEmail)
                            .addComponent(tfJelszo, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(dEmailBelepesLayout.createSequentialGroup()
                        .addComponent(btOk, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(btMegsem)
                        .addGap(21, 21, 21))))
        );

        dEmailBelepesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btMegsem, btOk});

        dEmailBelepesLayout.setVerticalGroup(
            dEmailBelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dEmailBelepesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(dEmailBelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dEmailBelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJelszo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(52, 52, 52)
                .addGroup(dEmailBelepesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btOk)
                    .addComponent(btMegsem))
                .addGap(87, 87, 87))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kangagui/image/kanga_logo.jpg"))); // NOI18N

        menuKilepes.setText("Kilépés");

        jmKilepes.setText("Kilépés");
        menuKilepes.add(jmKilepes);

        KangaMenu.add(menuKilepes);

        menuKolcsonzes.setText("Kölcsönzés");

        mKolcsonzes.setText("Kölcsönzés");
        mKolcsonzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mKolcsonzesActionPerformed(evt);
            }
        });
        menuKolcsonzes.add(mKolcsonzes);

        mVisszavetel.setText("Visszavétel");
        mVisszavetel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mVisszavetelActionPerformed(evt);
            }
        });
        menuKolcsonzes.add(mVisszavetel);

        menuEmlekezteto.setText("Emlékeztető");
        menuEmlekezteto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEmlekeztetoActionPerformed(evt);
            }
        });
        menuKolcsonzes.add(menuEmlekezteto);

        KangaMenu.add(menuKolcsonzes);

        menuElemek.setText("Tagok/hordozók kezelése");

        mTagokKezezelese.setText("Tagok kezelése");
        mTagokKezezelese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTagokKezezeleseActionPerformed(evt);
            }
        });
        menuElemek.add(mTagokKezezelese);

        mHordozokKezelese.setText("Hordozók kezelése");
        mHordozokKezelese.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mHordozokKezeleseActionPerformed(evt);
            }
        });
        menuElemek.add(mHordozokKezelese);

        KangaMenu.add(menuElemek);

        menuLekerdezes.setText("Lekérdezések");

        mLekerdez.setText("Lekérdezés");
        mLekerdez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mLekerdezActionPerformed(evt);
            }
        });
        menuLekerdezes.add(mLekerdez);

        KangaMenu.add(menuLekerdezes);

        setJMenuBar(KangaMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mTagokKezezeleseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTagokKezezeleseActionPerformed
        TagokKezeleseDialog tkd = new TagokKezeleseDialog(this, true);
        tkd.setVisible(true);
    }//GEN-LAST:event_mTagokKezezeleseActionPerformed

    private void mHordozokKezeleseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mHordozokKezeleseActionPerformed
        HordozokKezeleseDialog hkd = new HordozokKezeleseDialog(this, true);
        hkd.setVisible(true);
    }//GEN-LAST:event_mHordozokKezeleseActionPerformed

    private void mKolcsonzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mKolcsonzesActionPerformed
        KolcsonzesDialog kd = new KolcsonzesDialog(this, false);
        kd.setVisible(true);
    }//GEN-LAST:event_mKolcsonzesActionPerformed

    private void mVisszavetelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mVisszavetelActionPerformed
        VisszavetDialog vd = new VisszavetDialog(this, false);
        vd.setVisible(true);
    }//GEN-LAST:event_mVisszavetelActionPerformed

    private void menuEmlekeztetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEmlekeztetoActionPerformed
        dEmailBelepes.setVisible(true);
    }//GEN-LAST:event_menuEmlekeztetoActionPerformed

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        String email = tfEmail.getText();
        String jelszo = tfJelszo.getText();
        
        if (email==null || jelszo==null){
            JOptionPane.showMessageDialog(rootPane, "Nem adott meg egy adatot", "Hiányzó adat", JOptionPane.WARNING_MESSAGE);
        } else{
            dEmailBelepes.setVisible(false);
            EmlekeztetoDialog ed = new EmlekeztetoDialog(this, true, email, jelszo);
            ed.setVisible(true);
        }
    }//GEN-LAST:event_btOkActionPerformed

    private void btMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMegsemActionPerformed
        dEmailBelepes.setVisible(false);
    }//GEN-LAST:event_btMegsemActionPerformed

    private void mLekerdezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mLekerdezActionPerformed
        LekerdezesDialog ld = new LekerdezesDialog(this, true);
        ld.setVisible(true);
    }//GEN-LAST:event_mLekerdezActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KangaFoablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KangaFoablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KangaFoablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KangaFoablak.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KangaFoablak().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar KangaMenu;
    private javax.swing.JButton btMegsem;
    private javax.swing.JButton btOk;
    private javax.swing.JDialog dEmailBelepes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jmKilepes;
    private javax.swing.JMenuItem mHordozokKezelese;
    private javax.swing.JMenuItem mKolcsonzes;
    private javax.swing.JMenuItem mLekerdez;
    private javax.swing.JMenuItem mTagokKezezelese;
    private javax.swing.JMenuItem mVisszavetel;
    private javax.swing.JMenu menuElemek;
    private javax.swing.JMenuItem menuEmlekezteto;
    private javax.swing.JMenu menuKilepes;
    private javax.swing.JMenu menuKolcsonzes;
    private javax.swing.JMenu menuLekerdezes;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JPasswordField tfJelszo;
    // End of variables declaration//GEN-END:variables

    public void exitProc() {

        hibernate.HibernateUtil.getSessionFactory().close();

    }

}
