/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kangagui;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeFormatterBuilder;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

import org.hibernate.Session;

import pojos.Hordozo;
import pojos.Tag;

/**
 *
 * @author Droti
 */
public class KolcsonzesDialog extends javax.swing.JDialog {

    List<Tag> tagok;
    List<Hordozo> hordozok;
    

    public KolcsonzesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Kölcsönzés");
        setLocationRelativeTo(null);

        boxFrissit();

       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbKolcsonzo = new javax.swing.JComboBox();
        cbHordozo = new javax.swing.JComboBox();
        btKolcsonzes = new javax.swing.JButton();
        btBezar = new javax.swing.JButton();
        lbUzenet = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        datePicker = new com.github.lgooddatepicker.components.DatePicker();

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Hordozó");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Kölcsönzö");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Hordozó");

        cbKolcsonzo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbKolcsonzo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbHordozo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbHordozo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btKolcsonzes.setText("Kölcsönzés");
        btKolcsonzes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKolcsonzesActionPerformed(evt);
            }
        });

        btBezar.setText("Bezár");
        btBezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBezarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Határidő");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbKolcsonzo, 0, 555, Short.MAX_VALUE)
                        .addComponent(cbHordozo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(324, 324, 324)
                            .addComponent(lbUzenet, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btKolcsonzes)
                        .addGap(51, 51, 51)
                        .addComponent(btBezar))
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btBezar, btKolcsonzes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbKolcsonzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbHordozo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btKolcsonzes)
                    .addComponent(btBezar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(lbUzenet, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btKolcsonzesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKolcsonzesActionPerformed
        Tag kolcsonzo = (Tag) cbKolcsonzo.getSelectedItem();
        Hordozo hordozo = (Hordozo) cbHordozo.getSelectedItem();
        
        LocalDate datum = datePicker.getDate();
        
        if(datumEllenoriz(datum)){
        String hatarido = datumFormaz(datum);
        

        hordozo.setTag(kolcsonzo);
        hordozo.setKolcsonzesiHatarido(hatarido);
        
        Session session = hibernate.HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();
        session.update(hordozo);
        session.getTransaction().commit();
        session.close();

        boxFrissit();

        lbUzenet.setText("A kölcsönzés sikeres");
        }

    }//GEN-LAST:event_btKolcsonzesActionPerformed

    private void btBezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBezarActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btBezarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KolcsonzesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KolcsonzesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KolcsonzesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KolcsonzesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                KolcsonzesDialog dialog = new KolcsonzesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBezar;
    private javax.swing.JButton btKolcsonzes;
    private javax.swing.JComboBox cbHordozo;
    private javax.swing.JComboBox cbKolcsonzo;
    private com.github.lgooddatepicker.components.DatePicker datePicker;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbUzenet;
    // End of variables declaration//GEN-END:variables

    private void boxFrissit() {
        Session session = hibernate.HibernateUtil.getSessionFactory().openSession();
        tagok = session.createQuery("FROM Tag as t WHERE t.id!=0").list();
        hordozok = session.createQuery("FROM Hordozo as h WHERE h.tag.id=0").list();
        session.close();

        cbHordozo.setModel(new DefaultComboBoxModel<>(hordozok.toArray()));
        cbKolcsonzo.setModel(new DefaultComboBoxModel<>(tagok.toArray()));
    }
    
    private String datumFormaz(LocalDate datum){
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy.MM.dd");
        String datumString= datum.format(formatter);
        
        return datumString;
    }
    
    private boolean datumEllenoriz(LocalDate datum){
        LocalDate most =  LocalDate.now();
        
        if(datum.isBefore(most) || datum.isEqual(most)){
            JOptionPane.showMessageDialog(rootPane, "A mainál későbbi dátumot válasszon", "Figyelmeztetés", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }
}
