package pojos;
// Generated Dec 30, 2018 10:19:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name="tag"
    ,catalog="kanga_adatbazis"
)
public class Tag  implements java.io.Serializable {


     private Integer id;
     private String nev;
     private String email;
     private String telefonszam;
     private Set<Hordozo> hordozos = new HashSet<Hordozo>(0);

    public Tag() {
    }

    public Tag(String nev, String email, String telefonszam) {
        this.nev = nev;
        this.email = email;
        this.telefonszam = telefonszam;
    }
    
    

    public Tag(String nev, String email, String telefonszam, Set<Hordozo> hordozos) {
       this.nev = nev;
       this.email = email;
       this.telefonszam = telefonszam;
       this.hordozos = hordozos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nev", length=45)
    public String getNev() {
        return this.nev;
    }
    
    public void setNev(String nev) {
        this.nev = nev;
    }

    
    @Column(name="email", length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="telefonszam", length=45)
    public String getTelefonszam() {
        return this.telefonszam;
    }
    
    public void setTelefonszam(String telefonszam) {
        this.telefonszam = telefonszam;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="tag")
    public Set<Hordozo> getHordozos() {
        return this.hordozos;
    }
    
    public void setHordozos(Set<Hordozo> hordozos) {
        this.hordozos = hordozos;
    }

    @Override
    public String toString() {
        return nev+" ("+email+")";
    }




}


